In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import cv2

In [3]:
print(cv2.__version__)

4.10.0


In [4]:
#using imread('path') and 
img = cv2.imread(r'OIP.jpg', 1) # 1 for color image and 0 for grayscale
print(img)

[[[21 33 57]
  [21 33 57]
  [21 33 57]
  ...
  [23 33 63]
  [24 34 64]
  [24 34 64]]

 [[21 33 57]
  [21 33 57]
  [21 33 57]
  ...
  [23 33 63]
  [23 33 63]
  [23 33 63]]

 [[21 33 57]
  [21 33 57]
  [21 33 57]
  ...
  [23 33 63]
  [22 32 62]
  [22 32 62]]

 ...

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[60 60 60]
  [ 2  2  2]
  [ 0  0  0]
  ...
  [ 3  3  3]
  [ 4  4  4]
  [62 62 62]]

 [[60 60 60]
  [ 2  2  2]
  [ 0  0  0]
  ...
  [ 3  3  3]
  [ 4  4  4]
  [62 62 62]]]


* When you use cv2.imread() to load an image, OpenCV reads it in BGR (Blue, Green, Red) format.

In [5]:
img1 = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [6]:
img2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

In [7]:
img3 = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

In [8]:
img4 = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

In [9]:
#This is using for display the image
cv2.imshow('COLOR_image', img)
cv2.imshow('Gray_image', img1)
cv2.imshow('RGB_image', img2)
cv2.imshow('HSV_image', img3)
cv2.imshow('LAB_image', img4)

cv2.waitKey(0) #if we put 0 here means the image does not close until we press any key.(it will run continuously until the key press.)
cv2.destroyAllWindows()

In [10]:
#write the file in local directory

status = cv2.imwrite('hsvImage.png', img3)
print("Image written to file-system: ", status)

Image written to file-system:  True


In [11]:
# height, width, number of channels in image
dimensions = img.shape      #return a tuple with values height, width, and channels
height = img.shape[0]
width = img.shape[1]
channels = img.shape[2]
size1 = img.size


In [12]:
print('Image Dimension      :', dimensions)
print('Image Height         :', height)
print('Image Width          :', width)
print('Number of Channels   :', channels)
print('Image size           :', size1)

Image Dimension      : (474, 474, 3)
Image Height         : 474
Image Width          : 474
Number of Channels   : 3
Image size           : 674028


In [13]:
#split the image in 3 components(b, g, r) and merge it in different formats
b, g, r = cv2.split(img)

merged_img_bgr = cv2.merge((b, g, r))
merged_img_rgb = cv2.merge((r, g, b))

cv2.imshow('original image', img)
cv2.imshow('color_b_image', b)
cv2.imshow('color_g_image', g)
cv2.imshow('color_r_image', r)

cv2.imshow('merged_bgr', merged_img_bgr)
cv2.imshow('merged_rgb', merged_img_rgb)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# Resizing an image

width = 600
height = 650
dim = (width, height)

resized = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)

print('Resized Dimensions: ', resized.shape)
cv2.imshow('Original image', img)
cv2.imshow('Resized image', resized)

cv2.waitKey(0)
cv2.destroyAllWindows()

Resized Dimensions:  (650, 600, 3)


* Interpolation of image(https://www.cambridgeincolour.com/tutorials/image-interpolation.htm#google_vignette)

In [ ]:
#get image height, width
(h, w) = img.shape[:2]
#calculate center of the image
center = (w/2, h/2)

angle90 = 90
angle180 = 180
angle270 = 270

scale = 1.0

# Perform the counterclockwise rotation holding at the center
# 90 degrees
M = cv2.getRotationMatrix2D(center, angle90, scale)
rotated90 = cv2.warpAffine(img, M, (h, w))

# 180 degrees
M = cv2.getRotationMatrix2D(center, angle180, scale)
rotated180 = cv2.warpAffine(img, M, (h, w))

# 270 degrees
M = cv2.getRotationMatrix2D(center, angle270, scale)
rotated270 = cv2.warpAffine(img, M, (h, w))

cv2.imshow('Original img', img)
#cv2.waitKey(0)                  #waits until a key is pressed
#cv2.destroyAllWindows()         #destroys the windows showing image

cv2.imshow('90 degree rotated', rotated90)
#cv2.waitKey(0)                  #waits until a key is pressed
#cv2.destroyAllWindows()         #destroys the windows showing image

cv2.imshow('180 degree rotated', rotated180)
#cv2.waitKey(0)                  #waits until a key is pressed
#cv2.destroyAllWindows()         #destroys the windows showing image

cv2.imshow('270 degree rotated', rotated270)
cv2.waitKey(0)                  #waits until a key is pressed
cv2.destroyAllWindows()         #destroys the windows showing image

In [26]:
# Draw on image

cv2.circle(img, (100, 100), 60, (125, 233, 29), -1)
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.rectangle(img, (250, 200), (400, 450), (100, 200, 75), 10)
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.ellipse(img, (330, 330), (90, 80), 5, 0, 360, (255, 230, 100), -1)
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
#line

import numpy as np
cv2.line(img, (10, 0), (440, 440), (255, 255, 255), 15)
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:

#Add text to image
font = cv2.FONT_HERSHEY_COMPLEX
cv2.putText(img, 'Chhotu', (150, 170), font, 2, (200, 170, 160), 5)
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()